name: build
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "16.15.1"
      - run: npm ci
      - run: npm run ropm-ci
      - run: npm run validate
  npm-release:
    #only run this task for version-tagged releases
    if: startsWith(github.ref, 'refs/tags/v')
    needs: ci
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Set Release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "16.15.1"
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ./.npmrc
      - run: npm version ${{env.RELEASE_VERSION}} --no-git-tag-version
      #upload to npm
      - run: npm publish --access public